services:
  backend:
    image: daniele04/bugboard-backend:latest
    container_name: bugboard-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://bugboard-db.postgres.database.azure.com:5432/bugboard?sslmode=require
      DB_USERNAME: dbadmin
      DB_PASSWORD: "Passwordforte!"
